package com.example.rat3.scanner.ml

import org.json.JSONArray
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assume.assumeTrue
import org.junit.Test
import java.io.File

/**
 * Parity check: the Kotlin evaluators must reproduce the Python scikit-learn /
 * XGBoost models within a small tolerance.
 *
 * Oracle: `ml/parity_samples.json`, generated by `ml/export_models_for_android.py`
 * (feature vectors + each model's `predict_proba[:,1]` + the ensemble verdict).
 *
 * Reads the exported assets straight from `src/main/assets/ml/` — unit tests run
 * with the module directory (`android/app`) as the working directory.
 */
class MlEnsembleParityTest {

    private val assetsDir = File("src/main/assets/ml")
    private val parityFile = File("../../ml/parity_samples.json")

    private fun ensemble() = MlEnsemble.buildFrom { name ->
        File(assetsDir, name).takeIf { it.exists() }?.readText()
    }

    @Test
    fun `per-model probabilities match python within tolerance`() {
        assumeTrue("run export_models_for_android.py first", parityFile.exists() && assetsDir.exists())
        val samples = JSONArray(parityFile.readText())
        val mask = JSONArray(File(assetsDir, "variance_mask.json").readText())
        val maskArr = BooleanArray(mask.length()) { mask.getBoolean(it) }

        val ml = ensemble()
        var maxDelta = 0.0
        var checked = 0

        for (s in 0 until samples.length()) {
            val obj = samples.getJSONObject(s)
            val vecJson = obj.getJSONArray("vector")
            val vec = DoubleArray(vecJson.length()) { vecJson.getInt(it).toDouble() }

            val result = ml.classify(vec)
            val expected = obj.getJSONObject("models")
            val expEnsemble = obj.getJSONObject("ensemble")

            for (vote in result.perModel) {
                val py = expected.getDouble(vote.name) * 100.0
                val delta = kotlin.math.abs(py - vote.malwareProbPct)
                maxDelta = maxOf(maxDelta, delta)
                checked++
                // Stacking's KNN sub-model has inherent distance ties on binary data,
                // so its meta output can drift a little more than the pure tree models.
                val tol = 2.5
                assertTrue(
                    "sample $s ${vote.name}: kotlin=${"%.2f".format(vote.malwareProbPct)} python=${"%.2f".format(py)}",
                    delta <= tol,
                )
            }
            assertEquals(
                "sample $s ensemble verdict (kotlin score ${result.scorePct}, votes ${result.malVotes}/${result.malVotes + result.goodVotes})",
                expEnsemble.getString("verdict"),
                result.verdict,
            )
        }
        println("MlEnsembleParityTest: $checked model predictions checked, max delta ${"%.3f".format(maxDelta)}%")
        // keep the mask referenced so an accidental 241-vs-199 mismatch is obvious
        assertEquals(199, maskArr.count { it })
    }
}
