# RAT3 ProGuard Rules
# Keep scanner classes (needed for reflection-free operation)
-keep class com.example.rat3.scanner.** { *; }

# Keep MainActivity
-keep class com.example.rat3.MainActivity { *; }

# Flutter engine
-keep class io.flutter.** { *; }
-keep class io.flutter.embedding.** { *; }

# org.json (used for result serialization)
-keep class org.json.** { *; }

# Kotlin coroutines
-keepnames class kotlinx.coroutines.** { *; }

# Flutter's embedding references the Play Core split-install API for deferred components
# (dynamic feature modules). This app doesn't use deferred components or depend on
# com.google.android.play:core, so those classes are genuinely absent — R8 just needs to be
# told that's expected, not an error. (Rules as generated by AGP's own missing_rules.txt.)
-dontwarn com.google.android.play.core.splitcompat.SplitCompatApplication
-dontwarn com.google.android.play.core.splitinstall.SplitInstallException
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManager
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManagerFactory
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest$Builder
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest
-dontwarn com.google.android.play.core.splitinstall.SplitInstallSessionState
-dontwarn com.google.android.play.core.splitinstall.SplitInstallStateUpdatedListener
-dontwarn com.google.android.play.core.tasks.OnFailureListener
-dontwarn com.google.android.play.core.tasks.OnSuccessListener
-dontwarn com.google.android.play.core.tasks.Task